config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"

  resources :users , only:[:index] do
    resources :categories, only: [:index, :new, :destroy, :create, :show]  do
    resources :transferces,only: [:index, :new, :destroy, :create, :show]
  end
end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    return unless user.present?

    can :manage, Categorie, user: user
    can :manage, Transferce, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorie.rb
class Categorie < ApplicationRecord
  has_many :transferces
  belongs_to :user
  validates :name, presence: true
  validates :icon, presence: true
end

app/models/transferce.rb
class Transferce < ApplicationRecord
  has_many :categories
  belongs_to :user
  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :transferces
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_out_path_for(_resource)
    flash[:notice] = "notice:  you're loggedOut!!"
    new_user_session_path
  end

  def after_sign_in_path_for(_resource)
    user_categories_path(user_id: current_user.id)
  end

  def configure_permitted_parameters
    attributes = %i[name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categries = Categorie.includes(:transferces).where(user_id: params[:user_id])
  end

  def new
    @categorie = Categorie.new
  end

  def create
    @categorie = Categorie.new(categorie_params)
    @categorie.user_id = current_user.id

    if @categorie.save
      flash[:notice] = 'Transaction was successfully created.'
      redirect_to user_categories_path
    else
      flash[:error] = 'Error creating transaction'
      redirect_to user_categories_path(@categorie)
    end
  end

  def show; end

  def categorie_params
    params.require(:categorie).permit(:name, :icon)
  end

  def total(recipe)
    total = 0
    recipe.transferces.each do |transfer|
      total += transfer.amount
    end
    total
  end

  helper_method :total
end

app/controllers/transferces_controller.rb
class TransfercesController < ApplicationController
  before_action :set_categorie, only: %i[new create edit update destroy]
  def index
    @transcation = Transferce.where(user_id: current_user.id,
                                    categorie_id: params[:category_id]).order(created_at: :desc)
    @categorie = Categorie.find(params[:category_id])
  end

  def new
    @transferce = Transferce.new
    @categorie = Categorie.find(params[:category_id])
  end

  def create
    @transaction = Transferce.new(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.categorie_id = @categorie.id

    if @transaction.save
      flash[:notice] = 'Transaction was successfully created.'
      redirect_to user_category_transferces_path
    else
      flash[:error] = 'Error creating transaction'
      redirect_to user_category_transferces_path(@categorie)
    end
  end

  def set_categorie
    @categorie = Categorie.find(params[:category_id])
  end

  def transaction_params
    params.require(:transferce).permit(:name, :amount)
  end

  def total_in_catagory(_id)
    total = 0
    @transcation.each do |trans|
      total += trans.amount
    end
    total
  end
  helper_method :total_in_catagory
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  skip_load_and_authorize_resource
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<section  class="column col-between">
  <div>
    <%= render partial:'shared/navbar',
locals: {lbutton: "menu.svg", back_path:'', title: "Categories",  rbutton: :logout} %>

    <ul id="category_list" class="mh-110">
    <% if @categries.empty? %>
        <li class="card text-center">
         <h2>There are no categories</h2>
       </li>
    <% else %>
    <% @categries.each do |categorie| %>
     <%= link_to  user_category_transferces_path(user_id:current_user.id,category_id:categorie.id) do %>
      <li class="card">
       <div class="row row-between">
          <span class="row p-8">
            <span class="icon-20"><%= categorie.icon %></span>
            <span class="p-8"><%= categorie.name %></span>
          </span>
          <span class="p-8"><p>$<%=total(categorie)%></span>
        </div>
      </li>
      <% end %>
    <% end %>
    <% end %>
    </ul>
  </div>
  <div class="pv-8">
    <%= button_to "New Categorie", new_user_category_path, method: :get, class: "btn-full bg-secondary" %>
  </div>
</section>

app/views/categories/new.html.erb
<section>
<%= form_with model: @categorie ,class: 'form', url: user_categories_path do |f| %>
<%= render partial:'shared/navbar',
locals: {lbutton: "back.svg", back_path: :back, title: "New Category", form: f, button: "Save"} %>

           <div class="field">
             <%= f.text_field :name, value: @categorie.name, placeholder: "Enter Category Name", required: true%>
           </div>
           <div class="field">
               <%= f.select :icon, ["🍻","👔","🎵","🎉","🎁","🍼","🏠", "🐶",  "🍔"], value: @categorie.icon, required: true%>
           </div>
<% end %>
</section>

app/views/categories/show.html.erb
<h>THis is show</h>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.erb
<nav>
  <span class="width-80px">
    <%= link_to_unless back_path.empty?, image_tag(lbutton, id:'nav-lbutton', class: "filter-white", size: "30"), back_path %>
  </span>
  <h1><%= title %></h1>
  <div class="row row-end width-80px actions">
    <% if defined? form %>
      <%= form.submit button %>
    <% else %>
      <%= link_to image_tag('logout.svg', id:'nav-rbutton', class: "filter-white", size: "30"), destroy_user_session_path, data: { turbo_method: :delete } %>
    <% end %>
  </div>
</nav>

app/views/transferces/index.html.erb
<section  class="column col-between">
  <div>
    <%= render partial:'shared/navbar',
    locals: {lbutton: "back.svg", back_path: user_categories_path, title: "Transaction",  rbutton: :logout} %>

     <div class="card row row-between p-16">
        <span class="row">
          <span class="icon-20">
              <%=@categorie.icon %>
          </span>
          <%=@categorie.name %>
        </span>
          <span class="bold">
            $<%= total_in_catagory(@transcation) %>
         </span>
    </div>

    <ul id="category_list" class="mh-185">
      <% if @transcation.empty? %>
       <li class="card text-center">
         <h2>There are no expenses</h2>
       </li>
     <% else %>
      <% @transcation.each do |transaction| %>
        <li class="card">
          <div class="row row-between">
            <div class="column p-8">
              <span class="p-4-8"><%= transaction.name %></span>
              <span class="p-4-8 fs-12px"><%= transaction.created_at.strftime("%d %B %Y") %></span>
            </div>
            <span class="p-8 bold"><%= number_to_currency(transaction.amount) %></span>
          </div>
       </li>
      <% end %>
    <% end %>
  </div>
    <div class="pv-8">
      <%= button_to  "New Transaction", new_user_category_transferce_path, method: :get, class: "btn-full bg-secondary" %>
    </div>
</section>

app/views/transferces/new.html.erb
<section>
      <%= form_with model: @transferce,class: 'form', url: user_category_transferces_path(@categorie) do |f|%>
      <%= render partial:'shared/navbar',
locals: {lbutton: "back.svg", back_path: :back, title: "New Transaction", form: f, button: "Save"} %>

          <div class="field">
            <%= f.text_field :name, required: true, placeholder: :name%>
          </div>

          <div class="field">
            <%= f.number_field :amount, required: true, placeholder: :amount%>
          </div>

    <% end %>
</section>

app/views/welcome/index.html.erb
<section class="column col-between">
  <div class="row row-center vertical-90">
    <svg width="300px" height="300px" viewBox="0 0 30 30" id="Layer_1" style="enable-background:new 0 0 30 30;" version="1.1" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><style type="text/css">
  	.st0{fill:#FD6A7E;}
  	.st1{fill:#17B978;}
  	.st2{fill:#8797EE;}
  	.st3{fill:#41A6F9;}
  	.st4{fill:#37E0FF;}
  	.st5{fill:#2FD9B9;}
  	.st6{fill:#F498BD;}
  	.st7{fill:#FFDF1D;}
  	.st8{fill:#C6C9CC;}
  </style><path class="st1" d="M25,22v4c0,0.6-0.4,1-1,1H6c-0.6,0-1-0.4-1-1V13c0-0.6,0.4-1,1-1h18c0.6,0,1,0.4,1,1v4h-4.5  c-1.4,0-2.5,1.1-2.5,2.5c0,1.4,1.1,2.5,2.5,2.5H25z M20.5,18.5c-0.6,0-1,0.4-1,1s0.4,1,1,1s1-0.4,1-1S21.1,18.5,20.5,18.5z M18.5,2  C17.1,2,16,3.1,16,4.5S17.1,7,18.5,7S21,5.9,21,4.5S19.9,2,18.5,2z M14.7,10C14.9,9.6,15,9.2,15,8.7c0-1.7-1.3-3-3-3s-3,1.3-3,3  C9,9.2,9.1,9.6,9.3,10H14.7z"/></svg>
  </div>
  <div class="mv-2px p-16">
    <h1 class="text-center bg-light">Budget</h1>
  </div>
  <div>
    <span class="mv-2px pv-8">
      <%= button_to 'login',new_user_session_path , method: :get,class: "btn-full bg-primary"%>
    <span class="mv-2px pv-8">
      <%= button_to 'SignUp',new_user_registration_path,method: :get,class: "btn-full bg-light" %>
    </span>
  </div>
</section>